#!/usr/bin/env python
"""Draws some hats to the console"""

import os, sys, gettext, locale
_ = gettext.gettext
from optparse import OptionParser

usage = 'usage: invoke %prog, then enter a number when prompted'
parser = OptionParser(usage)
parser.add_option('-t', '--tophats',
                  action='store_true', dest='tophats', default=False,
                  help='draw tophats instead of fedoras')
parser.add_option('-l', '--locale',
                  type='string', dest='locale', default='en',
                  help='select a language to use, currently supports ja')

options, args = parser.parse_args()

# set up gettext
local_path = os.path.realpath(os.path.dirname(sys.argv[0]))
gettext.bindtextdomain('hatter', local_path)
gettext.textdomain('hatter')
lang = gettext.translation('hatter', local_path, [options.locale], fallback = True)
_ = lang.gettext

inputnum = raw_input(_('How many hats would you like? '))

try:
    numhats = int(inputnum)
except ValueError:
    print _('That doesn\'t seem like a valid integer!')
    sys.exit(1)

for hat in range(numhats):
    if options.tophats:
        print
        print '   \033[31;41m||||\033[0m'
    else:
        print '   \033[31m_  _\033[0m'
    print ' \033[31m__\033[41m||||\033[0;31m__\033[0m'
print
print _('done!')

